#!/bin/bash
#set -x
/media/fhenderson/HENDERSON/bin/rm-kernels
# NAME: rm-kernels
# PATH: /usr/local/bin
# DESC: Provide zenity radio list of kernels to remove

# DATE: Mar 10, 2017. Modified Mar 16, 2017.

# NOTE: Will not delete current kernel.

# Must be running as sudo
if [[ $(id -u) != 0 ]]; then
    zenity --error --text "root access required. Use: sudo rm-kernels"
    exit 99
fi

OLDIFS="$IFS"
IFS="|"
choices=()

current_version=$(uname -r)

for f in /boot/vmlinuz*
do
    if [[ $f == *"$current_version"* ]]; then continue; fi # skip current version
    if [[ $f =~ (.*).efi.signed ]]; then continue; fi # skip ones ending in .efi.signed as the will be removed the the package of the same name. - FJH 2017.08.11
    [[ $f =~ vmlinuz-(.*) ]]
    v=${BASH_REMATCH[1]}
    s=$(du -ch /boot/*-$v* | awk '/total/{print $1}')
    d=$(date --date $(stat -c %x $f) '+%b %d %Y')
    choices=("${choices[@]}" false "$v" "$d" "$s")
# choices=("${choices[@]}" false "$v" "$(date --date $(stat -c %x "$f") '+%b %d %Y')" "$s")
done

# adjust width & height below for your screen 640x480 default for 1920x1080 HD screen
# also adjust font="14" below if blue text is too small or too large

choices=(`zenity \
    --title "rm-kernels - Version: $current_version is excluded." \
    --list \
    --separator="$IFS" \
    --checklist --multiple \
        --text '<span foreground="blue" font="14">Check box next to kernel(s) to remove</span>' \
        --width=640 \
        --height=480 \
        --column "Select" \
        --column "Kernel Version Number" \
        --column "Last Access Date" \
        --column " Size " \
        "${choices[@]}"`)
IFS="$OLDIFS"

i=0
list=""
for choice in "${choices[@]}" ; do
    if [ "$i" -gt 0 ]; then list="$list- "; fi # append "-" from last loop
    ((i++))

    short_choice=$(echo $choice | cut -f1-2 -d"-")
    header_count=$(find /usr/src/linux-headers-$short_choice* -maxdepth 0 -type d | wc -l)

    # If -lowlatency and -generic are purged at same time the _all header directory
    # remains on disk for specific version with no -generic or -lowlatency below.
    if [[ $header_count -lt 3 ]]; then
        # Remove all w.x.y-zzz headers
        list="$list""linux-image-$choice- linux-headers-$short_choice"
    else
        # Remove w.x.y-zzz-flavour header only, ie -generic or -lowlatency
        list="$list""linux-image-$choice- linux-headers-$choice" 
    fi

done

if [ "$i" -gt 0 ] ; then
     apt-get purge $list
fi
